### ISSUE TITLE
CSScript.vsix does not install in Visual studio 2019

### ISSUE THREAD

**Issue by edwyn** [oleg-shilo/CS-Script.VSIX#2]
when double clicking on CSScript.vsix The extension can only be installed in VS 2017. although I also have VS 2019 intalled.

**Comment by edwyn** [comment]
Looks like support was added 5 days ago :)

**Comment by oleg-shilo** [comment]
Yes it is available right now.
The best way to get it is from the VS2019 extension manager:

![image](https://user-images.githubusercontent.com/16729806/56257662-541bf480-6110-11e9-9012-9fcf9ace3e41.png)

**Comment by SkyanSam** [comment]
VS support isn't working for 2017 though...

**Comment by oleg-shilo** [comment]
Closed as duplicated with #3
