### ISSUE TITLE
CS-Script doesn't work for VS 2019 & 2017. Version is outdated.

### ISSUE THREAD

**Issue by SkyanSam** [oleg-shilo/CS-Script.VSIX#3]
<img width="958" alt="Capturecsscr" src="https://user-images.githubusercontent.com/31390605/61599223-d2e36a80-abf4-11e9-823d-833842e48c50.PNG">
<img width="960" alt="Capturecs" src="https://user-images.githubusercontent.com/31390605/61599225-d971e200-abf4-11e9-9f81-c2da14afcbd1.PNG">
Please help I really want to use VS to allow people to create code addons outside of my Unity project. PLEASE PLEASE PLEASE. Also I've installed using Market Place. PLZ PLZ PLZ FIX!!

**Comment by oleg-shilo** [comment]
You will need to do what the error message is asking you to do "Download CS-Script". :)
Most likely it is the only thing that you need to do.

Fortunately you can do it from choco:

```
choco install cs-script
```

let me know how it goes and I will guide you through if any problems.

**Comment by SkyanSam** [comment]
Thank you. XD I thought I just had to install the addon I didn't realize that I have to install it with chocolately. All's up and running. 
![Uploading image.png…]()
If I have any more issues I'll let you know. Sorry about that. Probably should've read the instructions more clearer. xD

**Comment by SkyanSam** [comment]
<img width="960" alt="cssuccess" src="https://user-images.githubusercontent.com/31390605/61643451-ea603900-ac70-11e9-81f7-360c1be0dd6d.PNG">
