### ISSUE TITLE
Trying to use the extension for visual studio  2019

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/CS-Script.VSIX#4]
Moved from https://groups.google.com/g/cs-script/c/ZuKwBI5TGKU/m/CXqIWCCCBQAJ
Trying to use the extension for visual studio  2019 i  got the following

![image](https://user-images.githubusercontent.com/16729806/97065494-6924ee00-15f9-11eb-8c12-618db45703b5.png)

Cs-script extension is disabled , no compatible cs-script version found min3.4.2

But i have installed the 3.30.3.0
The same in vs studio 2015 and 2017  and for project based on framework .net 3.0 and 3.5
Please help , what can i do?
Thank a lot in advance

**Comment by oleg-shilo** [comment]
The extension tries to find the location of the script engine via dedicated envar. If it is empty or not pointing to the right location the extension will not work.

I suggest you try to see by yourself if the envar points to the right location. 

let me know what is the output of `echo %CSSCRIPT_DIR%` in your command prompt.

**Comment by allebonvi** [comment]
Hi all, thank you
the problem was exactly that of CSCSCRIP_INC pointing to a wrong place

**Comment by HuoYingCunCunZhang** [comment]
I have the same question, may I ask how to solve it @oleg-shilo

**Comment by oleg-shilo** [comment]
The second message in this thread is the answer:
![image](https://user-images.githubusercontent.com/16729806/130972375-e622f927-7fc5-40e0-b8a4-9b9a4d2ff76f.png)

**Comment by HuoYingCunCunZhang** [comment]
Thank you very much. I'll look for the corresponding environment variable.

**Comment by HuoYingCunCunZhang** [comment]
> The second message in this thread is the answer:
> ![image](https://user-images.githubusercontent.com/16729806/130972375-e622f927-7fc5-40e0-b8a4-9b9a4d2ff76f.png)

I use the command install cs-script
```
choco install cs-script 
```
![image](https://user-images.githubusercontent.com/46839162/131337157-271d764b-d30f-47af-809f-807e366897ab.png)

 How I configure it, please explain in detail
